### ISSUE TITLE
Automate Snapcraft remote build and deploy pipeline (preliminary research and store registration)

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-snap#14]
### Problem to solve

Right now the snap needs to built and deployment manually after each iteration of archethic-node.

### Solution

On each release of archethic-node, build and deploy pipeline will be triggered for archethic-snap.

- [x] Research on Snapcraft release management
- [x] Create a detailed documentation on snap installation and current prerequisites/assumptions (check the below PDF)
- [x] Register a Snap store brand account and sub accounts

[https://app.zenhub.com/files/456596617/840529d6-3fe7-45c5-989f-dbecaca18c4a/download](https://app.zenhub.com/files/456596617/840529d6-3fe7-45c5-989f-dbecaca18c4a/download)

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-snap/14?planning-poker) with ZenHub @roychowdhuryrohit-dev @I-Archer-Zero @nilesh-uniris @samuel-uniris
