### ISSUE TITLE
Customise node environment variables (design & review)

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-snap#17]
### Problem to solve

Right now all the archethic-node environment variables are either hardcoded or automatically generated during install time. But there may be scenarios when users need to customise certain variables (for ex. ports, network_type) during installation.

Users need to be able to customise at least the following ArchEthic node parameters.

- ARCHETHIC_HTTP_PORT
- ARCHETHIC_P2P_PORT
- ARCHETHIC_NETWORK_TYPE

### Solution

- [x] Design the possible user experiences through which we take inputs from user
- [x] Create a document for the same
[https://app.zenhub.com/files/456596617/63ababde-bc4c-4693-8089-7ade9e28ec3f/download](https://app.zenhub.com/files/456596617/63ababde-bc4c-4693-8089-7ade9e28ec3f/download)
- [x] Review document
- [ ] Present and finalise the user interaction

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-snap/17?planning-poker) with ZenHub @blackode @imnik11 @internet-zero @roychowdhuryrohit-dev @samuel-uniris

**Comment by AmodD** [comment]
- Can we precisely define which all variable/params we need to externalize ?
- Possibility to break each task as separate issue !
