### ISSUE TITLE
Add SSH port forwarding and access (research & review)

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-snap#18]
### What happened?

For some users we need to get SSH access for providing support. Right now there's no such feature of archethic-snap which enables developers to connect user miners via SSH.

### What is expected ?

To be able to diagnose system issues at user's end, the node should have SSH access exposed for us.

Following steps need to be implemented:

- [ ] Research on the possibility of SSH access within snap's sandbox confinement and list all access limitations (if any). If there are no limitations follow the next steps.
- [ ] Create a brief document explaining the result of the research findings.
- [ ] Review the document for feedback.

[https://app.zenhub.com/files/456596617/6b8c763b-c853-4e2c-a875-8a729b412440/download](https://app.zenhub.com/files/456596617/6b8c763b-c853-4e2c-a875-8a729b412440/download)

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-snap/18?planning-poker) with ZenHub @blackode @imnik11 @internet-zero @roychowdhuryrohit-dev @samuel-uniris

**Comment by AmodD** [comment]
let's break the issue with research part being a separate issue and the current issue depending on the research issue.
