### ISSUE TITLE
Automate Snapcraft remote build and deploy pipeline (documentation & review)

### ISSUE THREAD

**Issue by internet-zero** [archethic-foundation/archethic-snap#19]
This is the part where we take decisions, review and document the process which we will follow henceforth:

- [x] to manage the continuous build and deploy pipeline for ArchEthic snap manually or with the help of GitOps based automation.
- [x] to define the versioning of archethic-snap itself.
- [x] to define how closely the release cycle of archethic-node and archethic-snap is tied with each version change of archethic-node.
- [x] to define how to manage separate archethic-snap releases NOT as a result of archethic-snap version change.
- [x] to maintain separate `testnet`, `mainnet` and `develop` snap release tracks. Develop channel will follow the develop branch of archethic-node for enthusiastic users who wants to experience the latest updates (for ex: [Embedded DB](https://github.com/archethic-foundation/archethic-node/pull/271))

Doc: [https://app.zenhub.com/files/456596617/a2f51fef-ec9d-4a1d-a739-7b497e36ce00/download](https://app.zenhub.com/files/456596617/a2f51fef-ec9d-4a1d-a739-7b497e36ce00/download)

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-snap/19?planning-poker) with ZenHub @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by internet-zero** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-snap/19?planning-poker) with ZenHub @internet-zero

**Comment by roychowdhuryrohit-dev** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering-Workspace-61efec9c93391c001e69a6dc/issues/archethic-foundation/archethic-snap/19?planning-poker) with ZenHub @samuel-uniris
