### ISSUE TITLE
Implement Erlang hot reload via snap upgrade

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-snap#2]
### Problem to solve

Right now during the snap package upgrade, there's a downtime during which the service is stopped

### Solution

Using the Hot Reloading feature, we should be able to mitigate any downtime during node upgrade. 

- [x] Create post-refresh hook and do the following:
- [x] Copy the contents of snap folder to snap_data
- [x] Run the distillery upgrade inside bin folder
- [x] Solve issue - after snap refresh configure hook is checking pre-allocated ports and failing refresh process.
- [x] Test if upgrade is successful with zero downtime by checking archethic explorer at {localhost}:40000

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-snap/2?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
