### ISSUE TITLE
Customise node environment variables (implementation and testing)

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-snap#22]
### Problem to solve

Right now all the archethic-node environment variables are either hardcoded or automatically generated during install time. But there may be scenarios when users need to customise certain variables (for ex. ports, network_type) during installation.

Users need to be able to customise at least the following ArchEthic node parameters.

- ARCHETHIC_HTTP_PORT
- ARCHETHIC_P2P_PORT

This is a continuation from issue #17 where we do the feature implementation and testing.

### Solution

- [x] Fix service metadata so that it doesn't start right after installation.
- [x] Check if user-defined flags are getting registered during runtime.
- [x] Test the user journey.

The following user journey needs to be implemented.

1. Run `snap install archethic` to install archethic node but NOT start the server.
2. Run `sudo snap set archethic ports.http=40001
&& sudo snap set archethic ports.p2p=30003` to set all the correct env variables.
3. Finally to start archethic node server run `snap start archethic`.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-snap/22?planning-poker) with ZenHub @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
