### ISSUE TITLE
Autoscale Scylla-db configuration according to system resources

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-snap#3]
### Problem to solve

Right now Scylla-db installation is setup to manually configure exactly for 8GB memory and 2 cores. This should be flexible so that multiple users can install it.

### Solution

Maybe use the in-built Scylla-db auto configuration feature or we can also query system resources (cpu, memory) information and dedicate half of it to Scylla-db.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-snap/3?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris
