### ISSUE TITLE
Automate TPM certification and seed derivation

### ISSUE THREAD

**Issue by roychowdhuryrohit-dev** [archethic-foundation/archethic-snap#8]
### Problem to solve

Right now archethic-node snap installation configures with software implementation due to manual nature of TPM certification process required by TPM implementation.

### Solution

We can automate the whole TPM certification process and seed derivation for archethic.env file during the installation configuration i.e while executing `install` hook.

**Comment by internet-zero** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Product-and-Design-Workspace-61efe71b9083a90018250d89/issues/archethic-foundation/archethic-snap/8?planning-poker) with ZenHub @apoorv-2204 @blackode @imnik11 @roychowdhuryrohit-dev @samuel-uniris

**Comment by ghost** [comment]
Hello. 
We may not need the TPM certification, as it's a centralized method. (This method was used to select the primer investors by prioritize them as validator right)
However we will allow the use of Yubikey and others hardware key management, to identify a node chain through the POW.
This will be implemented with archethic-foundation/archethic-node#241
